product.product_controller:
  path: '/product'
  defaults:
    _controller: '\Drupal\product\Contrller\ProductController::display'
    _title: 'Product List'
  requirements:
    _permission: 'access content'

product.mydata_form:
  path: ‘/product/form/­mydata’
  defaults:
    _form: ‘\Drupal\product\Form­\MydataForm’
    _title: ‘MydataForm’
  requirements:
    _access: ‘TRUE’

product.display_table­_controller_display:
  path: ‘/product/hello/­table’
  defaults:
    _controller: ‘\Drupal\product\Cont­roller\DisplayTableC­ontroller::display’
    _title: ‘display’
  requirements:
    _permission: ‘access content’

product.delete_form:
  path: ‘/product/form/­delete/{cid}’
  defaults:
    _form: ‘\Drupal\product\Form­\DeleteForm’
    _title: ‘DeleteForm’
  requirements:
    _access: ‘TRUE